# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Lele Cao
title: Senior Data Scientist
email: caolele@gmail.com
website: www.github.com/

# Social links
twitter_username: facespics
github_username:  sproogen
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: chillwildlife
linkedin_username: caolele
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
projects_title: News

# Experience Section
experience_title: Experience

# Education Section
educaton_title: Education


# More Section
more_title: More about me ...
more_content: | # this will include new lines to allow paragraphs
  Patent: [CN106295703A](https://patents.google.com/patent/CN106295703A/en) (2017.1)

  Program Chair: [ECML-PKDD 2020](https://ecmlpkdd2020.net/organisation/programcommittee/)

  Master Thesis Supervision: 
  [Max Fischer](https://www.diva-portal.org/smash/get/diva2:1334684/FULLTEXT01.pdf) (Linköping University, 2019)
  [Alice Karnsund](http://kth.diva-portal.org/smash/get/diva2:1368129/FULLTEXT01.pdf) (KTH, 2019)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
