#theme: jekyll-theme-leap-day
remote_theme: mmistakes/minimal-mistakes
title: Lele (Larry) Cao
description: Ph.D. of Artificial Intelligence | AI Researcher | AI Developer
author: caolele
words_per_minute: 200
